name: chacra-env
channels:
  - conda-forge
  - defaults

dependencies: 
  ##### EDIT THIS LINE ######
  - openmpi=4.1.6=*external*
  ###########################
  - femto
  #### You may need to edit the openmm version to match your CUDA driver ####
  - openmm=8.1.2    
  ###########################################################################              
  - mdanalysis>=2.9.0
  - pdbfixer
  - pandas
  - scipy
  - tqdm
  - matplotlib
  - scikit-learn  
  - networkx
  - nglview
  - pre-commit
  - vmd-python
  - prolif
  
  
    
