name: chacra-dev
channels:
  - conda-forge
  - defaults

dependencies:
  - femto
  - openmm=8.1.2 # try 8.3 with openmpi pinned
  - mpi=1.0=openmpi
  - mdanalysis>=2.9.0
  - pdbfixer
  - pandas
  - scipy
  - tqdm
  - matplotlib
  - scikit-learn  
  - networkx
  - nglview
  - pre-commit
  - vmd-python
  - prolif
  
    
