name: chacra-env
channels:
  - conda-forge
  - defaults

dependencies:
  - femto
  - openmm=8.1.2 
  - mpi=1.0=openmpi
  - openmpi>=4.1         
  - mpi4py                
  - cuda-cudart>=12       
  - ucx>=1.15
  - ucx-proc=*=gpu        
  - nccl                  
  - mdanalysis>=2.9.0
  - pdbfixer
  - pandas
  - scipy
  - tqdm
  - matplotlib
  - scikit-learn  
  - networkx
  - nglview
  - pre-commit
  - vmd-python
  - prolif
  
    
